# Generated by Django 5.2.6 on 2025-12-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('moderateur', 'Modérateur'), ('invite', 'Invité'), ('expert', 'Expert')], default='inscrit', max_length=20),
        ),
    ]
