# Generated by Django 5.2.6 on 2025-09-25 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astuces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='astuce',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astuces_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astuce',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='astuces', to='astuces.categorie'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='astuce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='astuces.astuce'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favori',
            name='astuce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='astuces.astuce'),
        ),
        migrations.AddField(
            model_name='favori',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposition',
            name='astuce',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposition_origine', to='astuces.astuce'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recherche',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validation',
            name='astuce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='astuces.astuce'),
        ),
        migrations.AddField(
            model_name='validation',
            name='moderateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('utilisateur', 'astuce')},
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('utilisateur', 'astuce')},
        ),
    ]
