# Generated by Django 5.2.6 on 2025-12-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astuces', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='contenu',
            new_name='description',
        ),
        migrations.AddField(
            model_name='proposition',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='propositions', to='astuces.categorie'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='commentaire_moderation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_revision', 'En révision'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='proposition',
            name='titre',
            field=models.CharField(default='Ancienne proposition', max_length=255),
            preserve_default=False,
        ),
    ]
