# Generated by Django 5.2.6 on 2025-12-13 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astuces', '0003_rename_contenu_proposition_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='astuce',
            name='niveau_difficulte',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], default='debutant', max_length=20),
        ),
        migrations.AddField(
            model_name='proposition',
            name='niveau_difficulte',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], default='debutant', max_length=20),
        ),
        migrations.CreateModel(
            name='ImageAstuce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='astuces/%Y/%m/%d/')),
                ('legende', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('astuce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='astuces.astuce')),
            ],
            options={
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Terme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termes_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['terme'],
                'unique_together': {('terme',)},
            },
        ),
        migrations.AddField(
            model_name='astuce',
            name='termes',
            field=models.ManyToManyField(blank=True, related_name='astuces', to='astuces.terme'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='termes',
            field=models.ManyToManyField(blank=True, related_name='propositions', to='astuces.terme'),
        ),
    ]
