# Generated by Django 5.2.6 on 2025-12-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astuces', '0004_astuce_niveau_difficulte_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='terme',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='terme',
            name='terme',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='terme',
            name='createur',
        ),
    ]
