# Generated by Django 5.2.6 on 2025-12-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astuces', '0005_alter_terme_unique_together_alter_terme_terme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astuce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='astuces/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='propositions/%Y/%m/%d/'),
        ),
    ]
